# Generated by Django 3.1.10 on 2021-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='animes',
        ),
        migrations.AddField(
            model_name='profile',
            name='animes',
            field=models.ManyToManyField(to='core.Anime'),
        ),
    ]
