# Generated by Django 3.1.10 on 2021-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210508_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='core.Anime'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
