# Generated by Django 3.1.10 on 2021-05-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210512_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='characters_average',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='plot_average',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='visuals_average',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
